language: node_js
sudo: false
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
# とりあえずビルドするだけ
script: npm build
deploy:
  provider: script
  script: npx firebase deploy --token "$FIREBASE_TOKEN"
  on:
    branch: master
